version: "3.8"

services:
  mysql:
    container_name: mysql_8
    image: mysql:8.1
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql_8:/var/lib/mysql
      - ./data/mysql_dump:/tmp/dump
    environment:
      MYSQL_ROOT_PASSWORD: '123456'